# Generated by Django 6.0 on 2026-05-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
