# Generated by Django 6.0.5 on 2026-05-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_signup_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='mobile_no',
            new_name='password',
        ),
    ]
